on:
  workflow_dispatch:

jobs:
  test:
    name: test

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@master

      - name: Display the path
        run: echo $PATH
        shell: bash
