name: build smartdns rules dat files

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@master

      - name: Handle Data
        run: |
          mkdir tmp
          mkdir publish
          cd tmp

          wget -O gfwlist2dnsmasq.sh https://github.com/cokebar/gfwlist2dnsmasq/raw/master/gfwlist2dnsmasq.sh
          bash gfwlist2dnsmasq.sh -l -o gfwlist.raw.conf

          wget -O proxy.raw.conf https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Surge/Proxy/Proxy_Domain.list
          cat proxy.raw.conf | \
          sed 's/^#.*//' | \
          sed '/^\s*$/d' | \
          sed '/^[  ]*$/d' | \
          sed '/^$/d' | \
          sed 's/^\.//' \
          > overseas.raw.conf

          cat gfwlist.raw.conf overseas.raw.conf | sort | uniq > overseas.result.conf

          wget -O china_site.raw.conf https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Surge/ChinaMax/ChinaMax_Domain.list
          cat china_site.raw.conf | \
          sed 's/^#.*//' | \
          sed '/^\s*$/d' | \
          sed '/^[  ]*$/d' | \
          sed '/^$/d' | \
          sed 's/^\.//' \
          > china_site.result.conf

          wget -O china_ip.raw.conf https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPs/ChinaIPs_IP.txt
          cat china_ip.raw.conf | \
          sed 's/^#.*//' | \
          sed '/^\s*$/d' | \
          sed '/^[  ]*$/d' | \
          sed '/^$/d' \
          > china_ip.conf

          cp overseas.result.conf ../publish/overseas-site.list
          cp china_site.result.conf ../publish/china-site.list
          cp china_ip.conf ../publish/china-ip.list

        shell: bash

      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "`date '+%Y%m%d%H%M'`"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

      - name: Purge jsdelivr CDN
        run: |
          cd publish || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
          done
